### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Loghonox** [memsql/singlestore-spark-connector#76]
Testing a POC on my side I notice a big difference in performance between spark2 and spark3 same infrastructure same code, just using spark 2 vs spark3 and respective jdbc.
The gap can reach 10x bigger on spark3.
Could it be on the jdbc? any clue?

**Comment by AdalbertMemSQL** [comment]
Hi
Thanks for reaching out.
I would like to investigate, what is causing this performance degradation. 
Can you clarify the following questions?
 - What connector are you using for Spark 2 and Spark 3 and what is the version of the connector?
 - Are you connecting to the same database?
 - Does it happens during reading data from the SingleStore or writing?
 - Can you provide a reproducible example of the issue?

I doubt that JDBC is the root cause of this. The driver just reads and sends packets to the database. 10x performance degradation looks too big for so simple task. I suspect that the issue may be in the parallel read. In the newer version of the SingleStore Spark connector, this feature is completely redesigned.

**Comment by Loghonox** [comment]
Hello

Thanks for the reply, ofc here are the answer:

-   <dependency>
            <groupId>com.singlestore</groupId>
            <artifactId>singlestore-spark-connector_2.12</artifactId>
            <version>4.1.3-spark-3.3.0</version>
        </dependency>

vs 


 <dependency>
            <groupId>com.singlestore</groupId>
            <artifactId>singlestore-spark-connector_2.11</artifactId>
            <version>3.1.2-spark-2.4.7</version>
        </dependency>


        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.7.7</version>
        </dependency>

- same db nothing chg except version scala, spark and the connector
- it happens while reading,and writing, theres always a significant gap, between 10sec
- Something like:
     val windowedDF = Window.partitionBy("col_y", "col_x")
    val filtered = spark.read
      .option("enableParallelRead", "automatic")
      .option("parallelRead.Features", "readFromAggregators,readFromLeaves")
      .format(DefaultSource.SINGLESTORE_SOURCE_NAME_SHORT)
      .load(s"testdb.test1")
      .filter(col("col_x") === "7")
      .withColumn("max", functions.max(col("col_y_version")).over(windowedDF))
      .filter(col("max") === col("col_y_version"))
      .select("col_y", "col_x", "max")

**Comment by AdalbertMemSQL** [comment]
Can you please check if SQL pushdown generates the same queries for both cases? (here is more info on how to do this https://github.com/memsql/singlestore-spark-connector#debugging-sql-pushdown )

Also, can you try changing `parallelRead.Features` to `readFromLeaves`? In this way, it will perform parallel read in the same way for both versions of the SingleStore Spark connector.

**Comment by Loghonox** [comment]
checking the pushDown by explain I can see the queries are the same
Indeed adding parallelRead.Features to readFromLeaves helped a lot, we still have a small gap between 1/2sec shame spark3 wont be better but at least not as big gap as before

**Comment by AdalbertMemSQL** [comment]
Thanks for testing this. 
I think `readFromLeaves` works here better than `readFromAggregators` because of two reasons:
 - `readFromAggregators` performs repartitioning of data on the Spark side just after the read
 - the number of leaves in your cluster may be bigger than the number of aggregators and because of it, throughput is higher for `readFromLeaves`

`readFromAggregators` is a default option because `readFromLeaves` doesn't work in SingleStore Managed Service.
